"""add SDMX metadata registry

Revision ID: 12b008136560
Revises:
Create Date: 2026-09-02 01:29:59.383265
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '12b008136560'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sdmx_agency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agency_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agency_id')
    )
    op.create_table('sdmx_localized_label',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_pk', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_pk', 'language')
    )
    op.create_index(op.f('ix_sdmx_localized_label_entity_pk'), 'sdmx_localized_label', ['entity_pk'], unique=False)
    op.create_index(op.f('ix_sdmx_localized_label_entity_type'), 'sdmx_localized_label', ['entity_type'], unique=False)
    op.create_table('sdmx_structure_import',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=255), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('structures_received', sa.Integer(), nullable=False),
    sa.Column('structures_inserted', sa.Integer(), nullable=False),
    sa.Column('structures_updated', sa.Integer(), nullable=False),
    sa.Column('checksum_changes', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sdmx_codelist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agency_id', sa.String(length=128), nullable=False),
    sa.Column('codelist_id', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['sdmx_agency.agency_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agency_id', 'codelist_id', 'version')
    )
    op.create_table('sdmx_concept_scheme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agency_id', sa.String(length=128), nullable=False),
    sa.Column('scheme_id', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['sdmx_agency.agency_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agency_id', 'scheme_id', 'version')
    )
    op.create_table('sdmx_dataflow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agency_id', sa.String(length=128), nullable=False),
    sa.Column('dataflow_id', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_external_reference', sa.Boolean(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('dsd_agency_id', sa.String(length=128), nullable=True),
    sa.Column('dsd_id', sa.String(length=255), nullable=True),
    sa.Column('dsd_version', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['sdmx_agency.agency_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agency_id', 'dataflow_id', 'version')
    )
    op.create_table('sdmx_dsd',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agency_id', sa.String(length=128), nullable=False),
    sa.Column('dsd_id', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['sdmx_agency.agency_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agency_id', 'dsd_id', 'version')
    )
    op.create_table('sdmx_attribute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dsd_id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.String(length=255), nullable=False),
    sa.Column('attachment_level', sa.String(length=255), nullable=True),
    sa.Column('codelist_agency_id', sa.String(length=128), nullable=True),
    sa.Column('codelist_id', sa.String(length=255), nullable=True),
    sa.Column('codelist_version', sa.String(length=64), nullable=True),
    sa.Column('representation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['dsd_id'], ['sdmx_dsd.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dsd_id', 'concept_id')
    )
    op.create_table('sdmx_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codelist_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('parent_code', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['codelist_id'], ['sdmx_codelist.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codelist_id', 'code')
    )
    op.create_table('sdmx_concept',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concept_scheme_id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['concept_scheme_id'], ['sdmx_concept_scheme.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('concept_scheme_id', 'concept_id')
    )
    op.create_table('sdmx_dimension',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dsd_id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.String(length=255), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('codelist_agency_id', sa.String(length=128), nullable=True),
    sa.Column('codelist_id', sa.String(length=255), nullable=True),
    sa.Column('codelist_version', sa.String(length=64), nullable=True),
    sa.Column('representation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['dsd_id'], ['sdmx_dsd.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dsd_id', 'concept_id')
    )
    op.create_table('sdmx_measure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dsd_id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.String(length=255), nullable=False),
    sa.Column('representation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['dsd_id'], ['sdmx_dsd.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dsd_id', 'concept_id')
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sdmx_measure')
    op.drop_table('sdmx_dimension')
    op.drop_table('sdmx_concept')
    op.drop_table('sdmx_code')
    op.drop_table('sdmx_attribute')
    op.drop_table('sdmx_dsd')
    op.drop_table('sdmx_dataflow')
    op.drop_table('sdmx_concept_scheme')
    op.drop_table('sdmx_codelist')
    op.drop_table('sdmx_structure_import')
    op.drop_index(op.f('ix_sdmx_localized_label_entity_type'), table_name='sdmx_localized_label')
    op.drop_index(op.f('ix_sdmx_localized_label_entity_pk'), table_name='sdmx_localized_label')
    op.drop_table('sdmx_localized_label')
    op.drop_table('sdmx_agency')
    # ### end Alembic commands ###
